"""Transport-neutral adapter contract for the AACP Core conformance suite."""

from __future__ import annotations

from typing import Any, Protocol


class AACPAdapter(Protocol):
    """Behavior required from an implementation under test.

    The harness depends only on observable protocol behavior. Storage,
    database, transport and process architecture remain implementation details.
    """

    def reset(self) -> None: ...
    def new_task(self, *, status: str = "PENDING", unordered: bool = False) -> str: ...
    def command(self, task_id: str, *, message_id: str, sequence: int) -> dict[str, Any]: ...
    def deliver(self, message: dict[str, Any]) -> Any: ...
    def deliver_without_returning_ack(self, message: dict[str, Any]) -> None: ...
    def restart(self) -> None: ...
    def state(self, task_id: str) -> Any: ...
    def side_effect_count(self, key: str) -> int: ...
    def mutate(self, task_id: str, *, expected_version: int) -> Any: ...
    def transition(self, task_id: str, status: str, *, expected_version: int | None = None) -> Any: ...
    def complete(self, task_id: str, *, expected_version: int) -> Any: ...
    def cancel(self, task_id: str, *, expected_version: int) -> Any: ...
    def complete_task_and_push_then_crash(self) -> str: ...
    def remote_artifact(self, artifact_id: str) -> bool: ...
